// 保证 fetch 在 node 环境中有定义
if (typeof fetch === "undefined") {
    global.fetch = require("node-fetch");
}

import {
    ChatwootAccountDt,
    ChatwootContactDt,
    ChatwootConversationDt,
    ChatwootSenderDt,
    ChatwootWebHookDt,
    DdAppCreateDt,
    DdAppInfoDt,
    DdAppVerifyDt,
    DdMsgDt,
    EmailAppInfoDt,
    EmailMsgDt,
    EmailVerifyArgs,
    NotifyArgs,
    TplAppCreateDt,
    TplAppInfoDt,
    UserTokenDt,
    UserWhoamiDt,
    WxAppCreateDt,
    WxAppInfoDt,
    WxMsgDt
} from "./dt";

import {
    ApiDdApp,
    ApiDdAppList,
    ApiDdAppVerify,
    ApiDdChatwootUniqueId,
    ApiDdLinkUniqueId,
    ApiDdMsgList,
    ApiDdNotifyUniqueId,
    ApiDdRawUniqueId,
    ApiEmailApp,
    ApiEmailAppList,
    ApiEmailAppVerify,
    ApiEmailChatwootUniqueId,
    ApiEmailMsgList,
    ApiEmailNotifyUniqueId,
    ApiPing,
    ApiTplApp,
    ApiTplAppList,
    ApiTplNotifyUniqueId,
    ApiUserToken,
    ApiUserWhoami,
    ApiWxApp,
    ApiWxAppList,
    ApiWxChatwootUniqueId,
    ApiWxMdUniqueId,
    ApiWxMsgList,
    ApiWxNotifyUniqueId,
    ApiWxVerifyUniqueId,
    SecurityParamsType
} from "./stub"


export {
    DdAppCreateDt,
    DdAppInfoDt,
    DdAppVerifyDt,
    DdMsgDt,
    ChatwootConversationDt,
    ChatwootAccountDt,
    ChatwootContactDt,
    ChatwootSenderDt,
    ChatwootWebHookDt,
    NotifyArgs,
    EmailAppInfoDt,
    EmailVerifyArgs,
    EmailMsgDt,
    WxAppInfoDt,
    TplAppCreateDt,
    TplAppInfoDt,
    UserTokenDt,
    UserWhoamiDt,
    WxAppCreateDt,
    WxMsgDt,
    ApiPing,
    ApiDdApp,
    ApiDdAppList,
    ApiDdAppVerify,
    ApiDdMsgList,
    ApiDdChatwootUniqueId,
    ApiDdLinkUniqueId,
    ApiDdRawUniqueId,
    ApiDdNotifyUniqueId,
    ApiEmailApp,
    ApiEmailAppList,
    ApiEmailAppVerify,
    ApiEmailMsgList,
    ApiEmailNotifyUniqueId,
    ApiEmailChatwootUniqueId,
    ApiTplApp,
    ApiTplAppList,
    ApiTplNotifyUniqueId,
    ApiUserToken,
    ApiUserWhoami,
    ApiWxChatwootUniqueId,
    ApiWxMdUniqueId,
    ApiWxNotifyUniqueId,
    ApiWxApp, ApiWxAppList,
    ApiWxVerifyUniqueId,
    ApiWxMsgList,
    SecurityParamsType,
}
